# Generated by Django 3.2.5 on 2021-07-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataLatihKiper',
        ),
    ]
