# Generated by Django 3.2.5 on 2021-07-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm', '0002_auto_20210712_0129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataLatih',
            new_name='DataLatihKiper',
        ),
    ]
