# Generated by Django 3.2.5 on 2021-07-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm', '0003_rename_datalatih_datalatihkiper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalatihkiper',
            name='posisi',
        ),
    ]
